---

- name: "Make folder for {{ location }}"
  file:
    state: directory
    dest: "{{ output_folder }}/{{ location }}"
  tags:
    - destroy_nightly

- name: "Loop over products with product.yml"
  include: "2-product.yml"
  with_items: "{{ products }}"
  loop_control:
    loop_var: product
  tags:
    - destroy_nightly

# nightly delete code, unused:
- name: "Make folder"
  file:
    state: directory
    dest: "{{ output_folder }}/{{ location }}/destroy-nightly"
  tags:
    - destroy_nightly

- name: "Template destroy-nightly"
  template:
    src: "templates/destroy-nightly.sh.j2"
    dest: "{{ output_folder }}/{{ location }}/destroy-nightly/destroy-nightly.sh"
  tags:
    - destroy_nightly
